# Generated by Django 4.0.3 on 2022-04-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=50, unique=True, verbose_name='迭代名称')),
                ('state', models.CharField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0, max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=500, verbose_name='系统/页面/应用')),
                ('module_name', models.CharField(max_length=500, verbose_name='模块名称')),
                ('case_description', models.CharField(max_length=500, verbose_name='用例描述')),
                ('case_data', models.CharField(default='', max_length=500, verbose_name='测试数据')),
                ('remarks', models.CharField(default='', max_length=500, verbose_name='备注')),
                ('user', models.CharField(default='', max_length=200, verbose_name='执行人')),
                ('result', models.CharField(choices=[(0, '未执行'), (1, '失败'), (2, '挂起'), (3, '成功')], default=0, max_length=20, verbose_name='执行结果')),
                ('sprint_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SprintList.sprints')),
            ],
        ),
    ]
