# Generated by Django 4.0.3 on 2022-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default='', max_length=500, verbose_name='文件名称')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型,1是PostmanCollection，2是全局变量，3是环境变量，4是数据csv文件')),
                ('file_name', models.CharField(max_length=200, verbose_name='上传的文件名称')),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
            ],
        ),
    ]
